import js from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import prettierConfig from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        crypto: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        WebSocket: 'readonly',
        RTCPeerConnection: 'readonly',
        MediaRecorder: 'readonly',
        Worker: 'readonly',
        Notification: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        structuredClone: 'readonly',
        performance: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Image: 'readonly',
        location: 'readonly',
        URLSearchParams: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        XMLHttpRequest: 'readonly',
        Audio: 'readonly',
        FontFace: 'readonly',
        IntersectionObserver: 'readonly',
        MediaStream: 'readonly',
        RTCIceCandidate: 'readonly',
        RTCSessionDescription: 'readonly',
        File: 'readonly',
        libsignal: 'readonly',
        Strophe: 'readonly',
        $iq: 'readonly',
        $msg: 'readonly',
        $pres: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Event: 'readonly',
        getComputedStyle: 'readonly',
        IDBKeyRange: 'readonly',
        self: 'readonly',
      },
    },
    plugins: {
      import: importPlugin,
    },
    rules: {
      'import/no-unresolved': 'off',
      'import/order': [
        'warn',
        { 'newlines-between': 'always', alphabetize: { order: 'asc' } },
      ],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-control-regex': 'off',
    },
  },
  prettierConfig,
];
